<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ2sRrRZ\Systemcheck_CmsBundle_Tests_Controller_SystemcheckCmsControllerKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ2sRrRZ/Systemcheck_CmsBundle_Tests_Controller_SystemcheckCmsControllerKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerQ2sRrRZ.legacy');

    return;
}

if (!\class_exists(Systemcheck_CmsBundle_Tests_Controller_SystemcheckCmsControllerKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerQ2sRrRZ\Systemcheck_CmsBundle_Tests_Controller_SystemcheckCmsControllerKernelTestDebugContainer::class, Systemcheck_CmsBundle_Tests_Controller_SystemcheckCmsControllerKernelTestDebugContainer::class, false);
}

return new \ContainerQ2sRrRZ\Systemcheck_CmsBundle_Tests_Controller_SystemcheckCmsControllerKernelTestDebugContainer([
    'container.build_hash' => 'Q2sRrRZ',
    'container.build_id' => '54b4688e',
    'container.build_time' => 1643798486,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ2sRrRZ');
