<?php

// This file has been auto-generated by the Symfony Dependency Injection Component
// You can reference it in the "opcache.preload" php.ini setting on PHP >= 7.4 when preloading is desired

use Symfony\Component\DependencyInjection\Dumper\Preloader;

if (in_array(PHP_SAPI, ['cli', 'phpdbg'], true)) {
    return;
}

require dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'vendor/autoload.php';
(require __DIR__.'/Systemcheck_CmsBundle_Tests_Controller_SystemcheckCmsControllerKernelTestDebugContainer.php')->set(\ContainerQ2sRrRZ\Systemcheck_CmsBundle_Tests_Controller_SystemcheckCmsControllerKernelTestDebugContainer::class, null);
require __DIR__.'/ContainerQ2sRrRZ/getSystemcheckCmsBundle_SystemcheckCmsControllerService.php';
require __DIR__.'/ContainerQ2sRrRZ/getSystemcheckCmsBundle_SystemcheckCmsService.php';

$classes = [];
$classes[] = 'Systemcheck\CmsBundle\CmsBundle';
$classes[] = 'Symfony\Component\DependencyInjection\ContainerInterface';
$classes[] = 'Systemcheck\CmsBundle\Controller\CmsController';
$classes[] = 'Symfony\Component\DependencyInjection\ServiceLocator';

$preloaded = Preloader::preload($classes);
