parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
      

    Systemcheck\CmsBundle\:
        resource: '../../'
        exclude: '../../{vendor}'

    Systemcheck\CmsBundle\Controller\:
        resource: '../../Controller/*'
        public: true

